services:
  api:
    build: .
    container_name: jornal-ufc-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./database.sqlite:/app/database.sqlite
    restart: always